create table if not exists public.concept_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  concept_key text not null,
  term text not null,
  category text not null,
  is_correct boolean not null,
  answered_at timestamptz not null default now()
);

create index if not exists concept_attempts_user_key_idx
  on public.concept_attempts (user_id, concept_key, answered_at);

alter table public.concept_attempts enable row level security;

drop policy if exists "Users can read their own concept attempts" on public.concept_attempts;
create policy "Users can read their own concept attempts"
  on public.concept_attempts for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own concept attempts" on public.concept_attempts;
create policy "Users can insert their own concept attempts"
  on public.concept_attempts for insert
  with check (auth.uid() = user_id);

grant select, insert on public.concept_attempts to authenticated;
grant usage, select on sequence public.concept_attempts_id_seq to authenticated;
